sudo: false
language: node_js
notifications:
  slack: pdiateam:Pjgm2pL5O8xB3fMhTCWBjrhg
node_js:
  - '4.1'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
