sudo: false
language: node_js
notifications:
  slack: pdiateam:Pjgm2pL5O8xB3fMhTCWBjrhg
node_js:
  - '4.2.3'
  - '5.2.0'
#  - '0.12'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
